name: Reusable workflow example

on:
  workflow_call:


jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: message
      run: echo Linter Workflow Template
      
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # super-linter needs the full git history to get the
        # list of files that changed across commits
        fetch-depth: 0

    - uses: actions/setup-go@v4
      with:
        go-version: stable
        
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.59
